### ISSUE TITLE
Error: Tesla API: Get access token failed

### ISSUE THREAD

**Issue by adima959** [onokje/node-red-contrib-tesla#12] opened 2021-02-23 07:50 UTC
I´m running: 
Intel Nuc with HA 2021.2.3.
Node red: 1.1.3 v
node-red-contrib-tesla: 1.0.3

This used to work but recently stopped. 

When I try any action I get this error: **Error: Tesla API: Get access token failed**

Appreciate some help on this.

**Comment by delboy711** [comment] 2021-02-23 10:18
After having used node-red-contrib-tesla for some time very successfully (Thanks), I am having similar problems.

I deleted the tesla-config and when I created a new one the vehicle-list node gives me the response "Unauthorized".
I can log into my Tesla account normally, and do not use 2FA

**Comment by tombenzeen** [comment] 2021-02-24 11:23
same here...

**Comment by andrewgarfield** [comment] 2021-02-24 16:33
I am also having this issue for the last few days.

What's weird is that without changing anything (no changes to my node-red flows, no change to the library, etc) it will randomly start working and then stop working and then start working again.

**Comment by LudwigWen** [comment] 2021-02-26 10:57
same here, works fine again after update to 1.0.3 for some weeks. 
may be caused : Token from external lib teslajs is expired.

**Comment by tombenzeen** [comment] 2021-02-27 10:51
have also some issues with the Andorid App "Dashboard for Tesla. The fact that it works sometime and sometime not is probably caused by an Web Application Firewall whoch blocks to many Requests ?

**Comment by LudwigWen** [comment] 2021-02-28 09:23
temp solution until base library "teslajs" will be corrected:

https://github.com/mseminatore/TeslaJS/pull/225/commits/2e89bc3b6399a066e42e5d7c52fa09e8951a74e6

1. change .../NodeRed/node_modules/teslajs/src/auth.js to new version
2. sudo service nodered restart

**Comment by delboy711** [comment] 2021-02-28 10:32
Yes that works! Thanks.
I had to restart NodeRed. Restarting the flow was not sufficient.

**Comment by CommanderB** [comment] 2021-02-28 17:53
@LudwigWen Thank you! That worked. Had been struggling..

**Comment by adima959** [comment] 2021-02-28 19:25
@LudwigWen , thank you! :) Works for me too. 

One thing not working is "Remote start" anyone else experiencing that problem?

**Comment by Desmo996** [comment] 2021-03-18 21:21
I still can't get this to work and getting the "Get access token failed" message. I'm using the "id_s" number and I've checked auth.js and the fix above was already in place so not sure where to go from there.

**Comment by baku104788** [comment] 2021-04-06 01:03
I did the above fix and it worked for a while - now i just get "unauthorized" and it no longer works.

**Comment by frownbreaker** [comment] 2021-07-15 17:34
I think this is call fixed can this be closed?

**Comment by baku104788** [comment] 2021-08-05 16:17
I've done the manual update above and now I'm getting the get access token failed message again as of a few days ago. Anyone else seeing this?

**Comment by GaPhi** [comment] 2021-08-05 20:04
You can try `node node_modules/teslajs/samples/login.js <user> <pass>` command line...
In my case, it gives the same error message in both cases but the Tesla Android App or 
 Tesla Website logs in successfully with same user/pass and same network ; it is clearly in the HTTPS exchange (teslajs) that a mistake exists IMHO.

```
node node_modules/teslajs/samples/login.js 'email' 'pass'

Error: Login credentials rejected
    at /usr/src/node-red/node_modules/teslajs/src/auth.js:95:19
    at tryCallOne (/usr/src/node-red/node_modules/promise/lib/core.js:37:12)
    at /usr/src/node-red/node_modules/promise/lib/core.js:123:15
    at flush (/usr/src/node-red/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by onokje** [comment] 2021-11-25 23:11
Closing this, check the 2.0.0 update and this issue: https://github.com/onokje/node-red-contrib-tesla/issues/18 for more info.

**Closed by onokje** 2021-11-25 23:11 UTC
